!!python/object:tabularbench.config.config_run.ConfigRun
datafile_path: !!python/object/apply:pathlib.PosixPath
- data
- datasets
- whytrees_45019_MEDIUM.nc
dataset_size: !!python/object/apply:tabularbench.core.enums.DatasetSize
- 10000
device: !!python/object/apply:torch.device
- cuda
- 7
hyperparams:
  num_cpus: 8
  time_limit: 300
model_name: !!python/object/apply:tabularbench.core.enums.ModelName
- AutoGluon
openml_dataset_id: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i4
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  268AAA==
openml_dataset_name: Bioresponse
output_dir: !!python/object/apply:pathlib.PosixPath
- outputs
- '2024-08-08'
- 14-32-10
- autogluon-default-numerical_classification
- '45019'
- '#1'
seed: 1
task: !!python/object/apply:tabularbench.core.enums.Task
- classification
