!!python/object:tabularbench.config.config_run.ConfigRun
datafile_path: !!python/object/apply:pathlib.PosixPath
- data
- datasets
- whytrees_44125_MEDIUM.nc
dataset_size: !!python/object/apply:tabularbench.core.enums.DatasetSize
- 10000
device: !!python/object/apply:torch.device
- cuda
- 0
hyperparams:
  num_cpus: 8
  time_limit: 300
model_name: !!python/object/apply:tabularbench.core.enums.ModelName
- AutoGluon
openml_dataset_id: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i4
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  XawAAA==
openml_dataset_name: MagicTelescope
output_dir: !!python/object/apply:pathlib.PosixPath
- outputs
- '2024-08-08'
- 14-32-10
- autogluon-default-numerical_classification
- '44125'
- '#2'
seed: 2
task: !!python/object/apply:tabularbench.core.enums.Task
- classification
